# Generated by Django 5.1.2 on 2024-11-27 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_trainner_actividad_trainner_bmr_trainner_calorias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainner',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='trainner',
            name='bmr',
        ),
        migrations.RemoveField(
            model_name='trainner',
            name='calorias',
        ),
        migrations.RemoveField(
            model_name='trainner',
            name='imc',
        ),
        migrations.RemoveField(
            model_name='trainner',
            name='indice_cintura',
        ),
        migrations.RemoveField(
            model_name='trainner',
            name='masa_corporal',
        ),
        migrations.RemoveField(
            model_name='trainner',
            name='porcen_graso',
        ),
    ]
