# Generated by Django 5.1.2 on 2024-11-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_alter_trainner_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainner',
            name='bmr',
            field=models.CharField(max_length=100, null=True, verbose_name='bmr'),
        ),
    ]
