# Generated by Django 5.1.2 on 2024-11-27 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_alter_trainner_bmr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainner',
            name='bmr',
        ),
    ]
