# Generated by Django 5.1.2 on 2024-11-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0018_alter_trainner_porcen_graso'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainner',
            name='masa_corporal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='masa_corporal'),
        ),
    ]
