# Generated by Django 5.1.2 on 2024-11-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0020_alter_trainner_masa_corporal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainner',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='pes'),
        ),
    ]
