# Generated by Django 5.1.2 on 2024-11-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0023_trainner_calorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainner',
            name='calorias',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='calorias'),
        ),
    ]
