# Generated by Django 5.1.2 on 2024-11-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_remove_trainner_actividad_remove_trainner_bmr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainner',
            name='actividad',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True, verbose_name='cadera'),
        ),
    ]
