# Generated by Django 5.1.2 on 2024-11-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_trainner_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainner',
            name='actividad',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True, verbose_name='actividad'),
        ),
    ]
