# Generated by Django 5.1.2 on 2024-11-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0013_trainner_imc_trainner_indice_cintura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainner',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='imc'),
        ),
        migrations.AlterField(
            model_name='trainner',
            name='indice_cintura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='indice_cintura'),
        ),
    ]
