# Generated by Django 5.1.2 on 2024-11-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0022_alter_trainner_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainner',
            name='calorias',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='calorias'),
        ),
    ]
