# Generated by Django 5.0.6 on 2024-11-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0027_alter_trainner_actividad_alter_trainner_bmr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainner',
            name='bmr',
        ),
        migrations.RemoveField(
            model_name='trainner',
            name='calorias',
        ),
        migrations.RemoveField(
            model_name='trainner',
            name='imc',
        ),
        migrations.RemoveField(
            model_name='trainner',
            name='indice_cintura',
        ),
        migrations.RemoveField(
            model_name='trainner',
            name='masa_corporal',
        ),
        migrations.RemoveField(
            model_name='trainner',
            name='porcen_graso',
        ),
        migrations.AlterField(
            model_name='trainner',
            name='actividad',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='actividad'),
        ),
    ]
