# Generated by Django 5.0.6 on 2024-11-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0028_remove_trainner_bmr_remove_trainner_calorias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainner',
            name='actividad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='actividad'),
        ),
    ]
