# Generated by Django 5.0.6 on 2024-11-27 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0030_alter_trainner_actividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainner',
            name='actividad',
        ),
    ]
