# Generated by Django 5.0.6 on 2024-11-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0031_remove_trainner_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainner',
            name='actividad',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='actividad'),
        ),
    ]
