# Generated by Django 5.0.6 on 2024-11-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0033_alter_trainner_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainner',
            name='bmr',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='bmr'),
        ),
        migrations.AddField(
            model_name='trainner',
            name='calorias',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='calorias'),
        ),
        migrations.AddField(
            model_name='trainner',
            name='imc',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='imc'),
        ),
        migrations.AddField(
            model_name='trainner',
            name='indice_cintura',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='indice_cintura'),
        ),
        migrations.AddField(
            model_name='trainner',
            name='masa_corporal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='masa_corporal'),
        ),
        migrations.AddField(
            model_name='trainner',
            name='porcen_graso',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='porcen_graso'),
        ),
        migrations.AlterField(
            model_name='trainner',
            name='actividad',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='actividad'),
        ),
    ]
