# Generated by Django 5.0.6 on 2024-11-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0034_trainner_bmr_trainner_calorias_trainner_imc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainner',
            name='calorias',
        ),
        migrations.RemoveField(
            model_name='trainner',
            name='imc',
        ),
        migrations.RemoveField(
            model_name='trainner',
            name='indice_cintura',
        ),
        migrations.RemoveField(
            model_name='trainner',
            name='masa_corporal',
        ),
        migrations.RemoveField(
            model_name='trainner',
            name='porcen_graso',
        ),
    ]
