# Generated by Django 5.0.6 on 2024-11-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0035_remove_trainner_calorias_remove_trainner_imc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainner',
            name='bmr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='bmr'),
        ),
    ]
